name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest

    parameters:
      replace-existing:
        type: boolean
        default: false
        description: >
          If there is an existing installation of Google Chrome, replace it
          with the latest stable release?
      chrome-version:
        default: latest
        type: string
        description: >
          Version of Chrome to install, defaults to the latest stable release.
          To install an older release, specify a full chrome version number,
          e.g., 85.0.4183.83
          Only supported on centos and debian
          If replace-existing is false, this version is ignored.
      channel:
        description: |
          The release channel of Google Chrome to use. Defaults to 'stable'.
        type: enum
        enum: [ "stable", "beta" ]
        default: "stable"

    steps:
      - uses: actions/checkout@v3

      - run:
          name: Install Google Chrome
          environment:
            ORB_PARAM_CHROME_VERSION: <<parameters.chrome-version>>
            ORB_PARAM_REPLACE_EXISTING: <<parameters.replace-existing>>
            ORB_PARAM_CHANNEL: << parameters.channel >>
          command: <<include(scripts/install-chrome.sh)>>

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn

      - name: Build application
        run: yarn build

      - name: lighthouse mobile audit
        run: yarn lhci:mobile
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: lighthouse desktop audit
        run: yarn lhci:desktop
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}